[build-system]
requires = ["setuptools>=84.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "amplicontyper-installer"
version = "0.0.1"
description = "Installer for AmpliconTyper"
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
dev = [
    "pyinstaller>=6.0",
]
